// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7uEL4EmuAG999FVK4UZtiyDAJady63s',
    appId: '1:1067470759197:android:a98f58800cc8a806162df4',
    messagingSenderId: '1067470759197',
    projectId: 'khedoodating',
    storageBucket: 'khedoodating.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmEjtjHiLohSgHxABeGWp1eNmg_bR3XIA',
    appId: '1:1067470759197:ios:599fe82ddc190dbd162df4',
    messagingSenderId: '1067470759197',
    projectId: 'khedoodating',
    storageBucket: 'khedoodating.appspot.com',
    androidClientId: '1067470759197-0064du215irvufv7gglmg351l0vhcuam.apps.googleusercontent.com',
    iosClientId: '1067470759197-obeonjb47ejrmj2i0b93f7t4a9l9m9lk.apps.googleusercontent.com',
    iosBundleId: 'com.uchenna.fbolraffle',
  );
}
